spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    jdbc:
      platform: postgresql
      initialize-schema: always
    job:
      name: stopTestConfiguration-tx-job
#      enabled: false
  datasource:
    global:
      url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
      password: postgres
      username: postgres
    batch:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_batch
      password: postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
logging:
  level:
    root: info
    org.springframework.batch: debug

